In [130]:
import pandas as pd


saipe = pd.read_csv("Cleaned_Datasets/SAIPE.csv")
snap = pd.read_csv("Cleaned_Datasets/SNAP.csv")
mmg = pd.read_csv("Cleaned_Datasets/MMG.csv")

In [131]:
saipe["State"] = saipe["Postal"]
saipe

,State FIPS,County FIPS,Postal,Name,Poverty Estimate All Ages,90% CI Lower Bound,90% CI Upper Bound,Poverty Percent All Ages,90% CI Lower Bound.1,90% CI Upper Bound.1,...,90% CI Lower Bound.6,90% CI Upper Bound.6,Poverty Estimate Ages 0-4,90% CI Lower Bound.7,90% CI Upper Bound.7,Poverty Percent Ages 0-4,90% CI Lower Bound.8,90% CI Upper Bound.8,Year,State
0,0,0.0,US,United States,48452035,48217869,48686201,15.9,15.8,16,...,50429,50575,5110087.0,5061357.0,5158817.0,25.8,25.6,26.0,10,US
1,1,0.0,AL,Alabama,896117,879174,913060,19.1,18.7,19.5,...,40894,41960,94184.0,89925.0,98443.0,31.5,30.1,32.9,10,AL
2,1,1.0,AL,Autauga County,8152,6836,9468,14.9,12.5,17.3,...,44355,53371,NaN,NaN,NaN,NaN,NaN,NaN,10,AL
3,1,3.0,AL,Baldwin County,24728,20610,28846,13.4,11.2,15.6,...,46554,53734,NaN,NaN,NaN,NaN,NaN,NaN,10,AL
4,1,5.0,AL,Barbour County,7051,5884,8218,29.5,24.6,34.4,...,27484,32750,NaN,NaN,NaN,NaN,NaN,NaN,10,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25555,56,37.0,WY,Sweetwater County,4319,3593,5045,10,8.3,11.7,...,64776,74736,NaN,NaN,NaN,NaN,NaN,NaN,17,WY
25556,56,39.0,WY,Teton County,1767,1328,2206,8.3,6.2,10.4,...,62121,76069,NaN,NaN,NaN,NaN,NaN,NaN,17,WY
25557,56,41.0,WY,Uinta County,2013,1512,2514,9.7,7.3,12.1,...,55930,66602,NaN,NaN,NaN,NaN,NaN,NaN,17,WY
25558,56,43.0,WY,Washakie County,945,718,1172,11.3,8.6,14,...,44829,54665,NaN,NaN,NaN,NaN,NaN,NaN,17,WY
25559,56,45.0,WY,Weston County,776,610,942,11.5,9,14,...,48265,58361,NaN,NaN,NaN,NaN,NaN,NaN,17,WY

In [132]:
snap

     State                     Name  SNAP  Year
0       AL           Baldwin County   8.7    10
1       AL           Calhoun County  19.1    10
2       AL           Cullman County  14.3    10
3       AL            DeKalb County  16.0    10
4       AL            Elmore County   8.5    10
...    ...                      ...   ...   ...
6614  PRIC          Ponce Municipio  48.3    17
6615  PRIC       San Juan Municipio  27.4    17
6616  PRIC       Toa Alta Municipio  31.1    17
6617  PRIC       Toa Baja Municipio  24.7    17
6618  PRIC  Trujillo Alto Municipio  22.9    17

[6619 rows x 4 columns]

In [133]:
mmg

,FIPS,State,"County, State",FI Rate,Num FI Persons,Low Threshold in state,Low Threshold Type,High Threshold in state,High Threshold Type,% FI ≤ Low Threshold,% FI Btwn Thresholds,% FI > High Threshold,Child FI Rate,Num FI Children,% FI Children Below 185 FPL,% FI Children Above 185 FPL,Cost Per Meal,Weighted Annual Food Budget Shortfall,Year,Name
0,1001,AL,"Autauga County, Alabama",0.134,7140,1.3,SNAP,1.85,Other Nutrition Program,0.327,0.208,0.465,0.203,2980.0,0.51,0.49,2.58,3170830,10,Autauga County
1,1003,AL,"Baldwin County, Alabama",0.134,23570,1.3,SNAP,1.85,Other Nutrition Program,0.347,0.287,0.366,0.238,9720.0,0.59,0.41,2.64,10710730,10,Baldwin County
2,1005,AL,"Barbour County, Alabama",0.232,6440,1.3,SNAP,1.85,Other Nutrition Program,0.479,0.171,0.350,0.258,1600.0,0.87,0.13,2.53,2804540,10,Barbour County
3,1007,AL,"Bibb County, Alabama",0.157,3550,1.3,SNAP,1.85,Other Nutrition Program,0.358,0.288,0.354,0.249,1300.0,0.64,0.36,2.55,1558200,10,Bibb County
4,1009,AL,"Blount County, Alabama",0.126,7160,1.3,SNAP,1.85,Other Nutrition Program,0.410,0.305,0.285,0.254,3540.0,0.53,0.47,2.50,3081120,10,Blount County
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25135,56037,WY,"Sweetwater County, Wyoming",0.107,4750,1.3,SNAP,1.85,Other Nutrition Program,0.430,0.128,0.442,0.17,2030.0,0.51,0.49,3.14,2542000,17,Sweetwater County
25136,56039,WY,"Teton County, Wyoming",0.097,2220,1.3,SNAP,1.85,Other Nutrition Program,0.360,0.167,0.473,0.117,520.0,0.56,0.44,4.20,1592000,17,Teton County
25137,56041,WY,"Uinta County, Wyoming",0.128,2660,1.3,SNAP,1.85,Other Nutrition Program,0.562,0.074,0.365,0.189,1160.0,0.64,0.36,2.95,1340000,17,Uinta County
25138,56043,WY,"Washakie County, Wyoming",0.112,920,1.3,SNAP,1.85,Other Nutrition Program,0.505,0.172,0.323,0.174,350.0,0.74,0.27,3.16,497000,17,Washakie County
25139,56045,WY,"Weston County, Wyoming",0.131,940,1.3,SNAP,1.85,Other Nutrition Program,0.417,0.119,0.464,0.202,300.0,0.61,0.4,3.15,505000,17,Weston County

In [134]:
merged = pd.merge(saipe,snap, on=["State", "Name", "Year"], how="inner")
merged

,State FIPS,County FIPS,Postal,Name,Poverty Estimate All Ages,90% CI Lower Bound,90% CI Upper Bound,Poverty Percent All Ages,90% CI Lower Bound.1,90% CI Upper Bound.1,...,90% CI Upper Bound.6,Poverty Estimate Ages 0-4,90% CI Lower Bound.7,90% CI Upper Bound.7,Poverty Percent Ages 0-4,90% CI Lower Bound.8,90% CI Upper Bound.8,Year,State,SNAP
0,1,3.0,AL,Baldwin County,24728,20610,28846,13.4,11.2,15.6,...,53734,NaN,NaN,NaN,NaN,NaN,NaN,10,AL,8.7
1,1,15.0,AL,Calhoun County,23974,20930,27018,20.9,18.2,23.6,...,41452,NaN,NaN,NaN,NaN,NaN,NaN,10,AL,19.1
2,1,43.0,AL,Cullman County,14455,12204,16706,18.2,15.4,21,...,42727,NaN,NaN,NaN,NaN,NaN,NaN,10,AL,14.3
3,1,49.0,AL,DeKalb County,14331,11742,16920,20.3,16.6,24,...,37862,NaN,NaN,NaN,NaN,NaN,NaN,10,AL,16.0
4,1,51.0,AL,Elmore County,10299,8444,12154,13.8,11.3,16.3,...,58112,NaN,NaN,NaN,NaN,NaN,NaN,10,AL,8.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6502,55,133.0,WI,Waukesha County,21319,18172,24466,5.5,4.7,6.3,...,75444,NaN,NaN,NaN,NaN,NaN,NaN,17,WI,3.3
6503,55,139.0,WI,Winnebago County,19677,16997,22357,12.4,10.7,14.1,...,52186,NaN,NaN,NaN,NaN,NaN,NaN,17,WI,10.6
6504,55,141.0,WI,Wood County,9093,7724,10462,12.3,10.4,14.2,...,48918,NaN,NaN,NaN,NaN,NaN,NaN,17,WI,14.7
6505,56,21.0,WY,Laramie County,9008,7364,10652,9.9,8.1,11.7,...,57808,NaN,NaN,NaN,NaN,NaN,NaN,17,WY,7.4
6506,56,25.0,WY,Natrona County,8559,7041,10077,11.5,9.5,13.5,...,57199,NaN,NaN,NaN,NaN,NaN,NaN,17,WY,7.6

In [135]:
merged.Year.value_counts()

Year
17    823
16    817
15    816
13    814
14    814
12    811
11    808
10    804
Name: count, dtype: int64

In [136]:
merged = pd.merge(merged,mmg, on=["State", "Name", "Year"], how="inner")
merged

,State FIPS,County FIPS,Postal,Name,Poverty Estimate All Ages,90% CI Lower Bound,90% CI Upper Bound,Poverty Percent All Ages,90% CI Lower Bound.1,90% CI Upper Bound.1,...,High Threshold Type,% FI ≤ Low Threshold,% FI Btwn Thresholds,% FI > High Threshold,Child FI Rate,Num FI Children,% FI Children Below 185 FPL,% FI Children Above 185 FPL,Cost Per Meal,Weighted Annual Food Budget Shortfall
0,1,3.0,AL,Baldwin County,24728,20610,28846,13.4,11.2,15.6,...,Other Nutrition Program,0.347,0.287,0.366,0.238,9720.0,0.59,0.41,2.64,10710730
1,1,15.0,AL,Calhoun County,23974,20930,27018,20.9,18.2,23.6,...,Other Nutrition Program,0.468,0.224,0.308,0.254,6760.0,0.69,0.31,2.59,8925230
2,1,43.0,AL,Cullman County,14455,12204,16706,18.2,15.4,21,...,Other Nutrition Program,0.440,0.346,0.214,0.263,4890.0,0.6,0.4,2.63,4925390
3,1,49.0,AL,DeKalb County,14331,11742,16920,20.3,16.6,24,...,Other Nutrition Program,0.517,0.391,0.091,0.312,5630.0,0.69,0.32,2.51,4843230
4,1,51.0,AL,Elmore County,10299,8444,12154,13.8,11.3,16.3,...,Other Nutrition Program,0.314,0.204,0.481,0.213,3960.0,0.56,0.44,2.57,4941310
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6502,55,133.0,WI,Waukesha County,21319,18172,24466,5.5,4.7,6.3,...,"SNAP, Other Nutrition Programs",0.466,NaN,0.534,0.122,10770.0,0.37,0.63,3.03,13195000
6503,55,139.0,WI,Winnebago County,19677,16997,22357,12.4,10.7,14.1,...,"SNAP, Other Nutrition Programs",0.623,NaN,0.377,0.158,5580.0,0.61,0.39,2.96,8680000
6504,55,141.0,WI,Wood County,9093,7724,10462,12.3,10.4,14.2,...,"SNAP, Other Nutrition Programs",0.725,NaN,0.275,0.165,2630.0,0.77,0.23,2.91,3515000
6505,56,21.0,WY,Laramie County,9008,7364,10652,9.9,8.1,11.7,...,Other Nutrition Program,0.387,0.147,0.466,0.154,3490.0,0.52,0.48,3.14,5676000
6506,56,25.0,WY,Natrona County,8559,7041,10077,11.5,9.5,13.5,...,Other Nutrition Program,0.398,0.131,0.471,0.174,3400.0,0.51,0.49,3.06,5350000

In [137]:
merged.Year.value_counts()

Year
17    823
16    817
15    816
13    814
14    814
12    811
11    808
10    804
Name: count, dtype: int64

In [138]:
laus = pd.read_csv("Cleaned_Datasets/LAUS.csv", index_col=0)
laus

,LAUS Code,State FIPS Code,County FIPS Code,County Name/State Abbreviation,Year,Labor Force,Employed,Unemployed,Unemployment Rate (%),State FIPS,County FIPS
0,CN0100100000000,1.0,1.0,"Autauga County, AL",10,25972.0,23688.0,2284.0,8.8,1.0,1.0
1,CN0100300000000,1.0,3.0,"Baldwin County, AL",10,84269.0,75943.0,8326.0,9.9,1.0,3.0
2,CN0100500000000,1.0,5.0,"Barbour County, AL",10,10307.0,9057.0,1250.0,12.1,1.0,5.0
3,CN0100700000000,1.0,7.0,"Bibb County, AL",10,9012.0,8000.0,1012.0,11.2,1.0,7.0
4,CN0100900000000,1.0,9.0,"Blount County, AL",10,25142.0,22706.0,2436.0,9.7,1.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...
25779,CN7215100000000,72.0,151.0,"Yabucoa Municipio, PR",17,9343.0,7877.0,1466.0,15.7,72.0,151.0
25780,CN7215300000000,72.0,153.0,"Yauco Municipio, PR",17,11345.0,9594.0,1751.0,15.4,72.0,153.0
25781,NaN,NaN,NaN,NaN,17,NaN,NaN,NaN,NaN,NaN,NaN
25782,"SOURCE: BLS, LAUS",NaN,NaN,NaN,17,NaN,NaN,NaN,NaN,NaN,NaN
25783,"May 19, 2026",NaN,NaN,NaN,17,NaN,NaN,NaN,NaN,NaN,NaN

In [139]:
merged = pd.merge(merged, laus, on=["State FIPS", "County FIPS", "Year"], how="inner")
merged

,State FIPS,County FIPS,Postal,Name,Poverty Estimate All Ages,90% CI Lower Bound,90% CI Upper Bound,Poverty Percent All Ages,90% CI Lower Bound.1,90% CI Upper Bound.1,...,Cost Per Meal,Weighted Annual Food Budget Shortfall,LAUS Code,State FIPS Code,County FIPS Code,County Name/State Abbreviation,Labor Force,Employed,Unemployed,Unemployment Rate (%)
0,1,3.0,AL,Baldwin County,24728,20610,28846,13.4,11.2,15.6,...,2.64,10710730,CN0100300000000,1.0,3.0,"Baldwin County, AL",84269.0,75943.0,8326.0,9.9
1,1,15.0,AL,Calhoun County,23974,20930,27018,20.9,18.2,23.6,...,2.59,8925230,CN0101500000000,1.0,15.0,"Calhoun County, AL",52020.0,46200.0,5820.0,11.2
2,1,43.0,AL,Cullman County,14455,12204,16706,18.2,15.4,21,...,2.63,4925390,CN0104300000000,1.0,43.0,"Cullman County, AL",36291.0,32554.0,3737.0,10.3
3,1,49.0,AL,DeKalb County,14331,11742,16920,20.3,16.6,24,...,2.51,4843230,CN0104900000000,1.0,49.0,"DeKalb County, AL",31183.0,27322.0,3861.0,12.4
4,1,51.0,AL,Elmore County,10299,8444,12154,13.8,11.3,16.3,...,2.57,4941310,CN0105100000000,1.0,51.0,"Elmore County, AL",37049.0,33728.0,3321.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6430,55,133.0,WI,Waukesha County,21319,18172,24466,5.5,4.7,6.3,...,3.03,13195000,CN5513300000000,55.0,133.0,"Waukesha County, WI",221151.0,214657.0,6494.0,2.9
6431,55,139.0,WI,Winnebago County,19677,16997,22357,12.4,10.7,14.1,...,2.96,8680000,CN5513900000000,55.0,139.0,"Winnebago County, WI",92943.0,90166.0,2777.0,3.0
6432,55,141.0,WI,Wood County,9093,7724,10462,12.3,10.4,14.2,...,2.91,3515000,CN5514100000000,55.0,141.0,"Wood County, WI",38332.0,37022.0,1310.0,3.4
6433,56,21.0,WY,Laramie County,9008,7364,10652,9.9,8.1,11.7,...,3.14,5676000,CN5602100000000,56.0,21.0,"Laramie County, WY",48056.0,46216.0,1840.0,3.8
6434,56,25.0,WY,Natrona County,8559,7041,10077,11.5,9.5,13.5,...,3.06,5350000,CN5602500000000,56.0,25.0,"Natrona County, WY",42094.0,39935.0,2159.0,5.1

In [140]:
merged.Year.value_counts()

Year
17    814
16    808
15    807
13    805
14    805
12    802
11    799
10    795
Name: count, dtype: int64

In [141]:
merged.to_csv("dataset.csv", index=False)